version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "4001:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "4002:6379"

volumes:
  postgres:
