version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "4001:5432"
    environment:
      POSTGRES_USER: sw
      POSTGRES_PASSWORD: sw
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    restart: always
    ports:
      - "4002:6379"

volumes:
  postgres:
